##############################Spring
spring:

  h2:
    console:
      enabled: true
      path: /javamyadmin

  jpa:
    database: POSTGRESQL
    show-sql: true
    driverClassName: org.postgresql.Driver
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/notesapp
    username: postgres
    password:
#############################Actuator
#management:
#  security:
#    enabled: true #false to enable endpoints
