##############################Spring
spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

#############################Actuator
#management:
#  security:
#    enabled: false #false to enable endpoints
#############################
#endpoints:
#  beans:
#    id: springbeans
#    sensitive: false
#############################